# Generated by Django 3.1.4 on 2020-12-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opposition', models.CharField(max_length=32)),
                ('players', models.ManyToManyField(related_name='players', to='mainapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='VoteCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.match')),
                ('player_voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by', to='mainapp.player')),
                ('player_voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='mainapp.player')),
            ],
            options={
                'unique_together': {('player_voted_by', 'match')},
                'index_together': {('player_voted_by', 'match')},
            },
        ),
    ]
