# Generated by Django 3.1.4 on 2020-12-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201215_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votecounter',
            name='votes',
        ),
        migrations.AlterField(
            model_name='votecounter',
            name='player_voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_voted_by', to='mainapp.player'),
        ),
        migrations.AlterField(
            model_name='votecounter',
            name='player_voted_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_voted_for', to='mainapp.player'),
        ),
    ]
