# Generated by Django 3.1.4 on 2020-12-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201215_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteCounter',
        ),
    ]
