# Generated by Django 3.1.4 on 2020-12-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_player_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='votes',
        ),
        migrations.AddField(
            model_name='match',
            name='home_or_away',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Away')], default='H', max_length=1),
        ),
        migrations.CreateModel(
            name='PlayerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.match')),
                ('player_voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_voted_by', to='mainapp.player')),
                ('player_voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_voted_for', to='mainapp.player')),
            ],
            options={
                'unique_together': {('player_voted_by', 'match')},
                'index_together': {('player_voted_by', 'match')},
            },
        ),
    ]
